# ChickTech
remote_theme: mmistakes/minimal-mistakes
title: Galaxy NGC 891
include: ["_pages"]

author:
  name: "Kaitlin Khosravi"
  avatar: "http://news.blr.com/app/uploads/sites/3/2016/10/Llama-1.jpg"
  bio: "
